### ISSUE TITLE
advanced usage

### ISSUE THREAD

**Issue by valour01** [mrname/haralyzer#11]
Hi, It seems that haralyzer doesn't provide api for the detail information for every entry. Do you know how can I get the detailed info for every entry(you know one entry represent one single request in .har). Espeacilly the content-type. timings. status code and so on. Many Thanks

**Comment by mrname** [comment]
The entries of each page are stored in `HarPage.entries`. Check out the docs below for a code example.

https://github.com/mrname/haralyzer#advanced-usage

I hope that clears things up a bit, let me know if you have any other questions. Sorry for the delay in my response, I am on vacation and have limited internet access, but I will do my best to respond to any other questions you might have as quickly as possible.

**Comment by valour01** [comment]
Hi. I see. I was wondering is it available to classify the size and load time for js. css. image. audio by HTTP version. Many Thanks

**Comment by mrname** [comment]
Sorry for the delay @valour01. Although you can pull this out of the `request` key of each `entry` like so:

```python
for entry in page.entries:
    entry['request']['httpVersion']
```

there is currently no great way to filter by HTTP version. Let me work up a pull request for you.

**Comment by valour01** [comment]
I see. thank you very much.

**Comment by mrname** [comment]
@valour01 check out the PR above when you get a second and let me know if this works for you.

**Comment by valour01** [comment]
@mrname  Thank you very much. It works

**Comment by mrname** [comment]
Sorry for the delay @valour01 will merge this in the next day or two for you.

**Comment by mrname** [comment]
Sorry for the delay, life has been more hectic that usual.

Feel free to open up another issue if you need anything @valour01
