### ISSUE TITLE
Entries with no `pageref` field

### ISSUE THREAD

**Issue by mrname** [mrname/haralyzer#23]
Some entries in a HAR file might not specify `pageref`. This is fair enough, because according to the spec, this is optional. Entries with no `pageref` still need to be considered as valid requests. As of right now, even a single entry missing a `pageref` blows everything up.

```
File "/usr/local/lib/python3.6/site-packages/cached_property.py", line 32, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.6/site-packages/haralyzer/assets.py", line 414, in url
    return self.entries[0]['request']['url']
  File "/usr/local/lib/python3.6/site-packages/cached_property.py", line 32, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.6/site-packages/haralyzer/assets.py", line 420, in entries
    if entry['pageref'] == self.page_id:
KeyError: 'pageref'
```

We need to figure out a safe way to respect these entries despite the fact that we cannot add them to any of the `HarPage` objects of the parser. Most likely, we will always create a default `HarPage` with an ID of `unknown`, and all entries missing `pageref` will get grouped into there.

**Comment by luckyrantanplan** [comment]
as a workaround I have to write this : 
`for entry in har_parser.har_data['entries']:
            if 'pageref' not in entry:
                entry['pageref'] = "unknow"`

**Comment by mrname** [comment]
Thanks for the feedback @luckyrantanplan. I have been working on a bugfix in a similar fashion on this branch, will try to finish it up soon, but feel free to pick up work on it as well:

https://github.com/mrname/haralyzer/tree/pageref_bugfix

**Comment by mbehn** [comment]
Hi, thank you for your help on this. I wanted to see how close you might be to pushing a fix? It would be super helpful.

**Comment by mrname** [comment]
Hey @mbehn ! I do apologize as I get busy and fell off of this. I believe it is very close, I just hit a small roadblock when I got some unexpected test failures. I will push the urgency of this request up and try to finish it off for you all as soon as possible.

**Comment by mrname** [comment]
@mbehn I went ahead and opened a pull request for my updates:

https://github.com/mrname/haralyzer/pull/26/

There are a couple of tricky things in there so I just need to read through and double check the logic. Please feel free to do the same if you have time and I will try to get this launched soon.
