### ISSUE TITLE
Py3.7 has made async a reserved keyword

### ISSUE THREAD

**Issue by NickPancakes** [mrname/haralyzer#24]
Unfortunately, importing haralyzer is currently failing with a SyntaxError on python 3.7 due to "async" being the name of a kwarg on the get_load_time function of HarPage (assets.py, line 344)

This is because async is now a reserved keyword as of 3.7.0: https://docs.python.org/3.7/whatsnew/3.7.html

Sorry for no PR at the moment, perhaps in a day or two if I am not beaten to the punch.

**Comment by mrname** [comment]
Killer, thanks for the report @NickPancakes! Will try to do the same if you don't beat me to it.
