### ISSUE TITLE
cached-property is not automatically installed when using pip install

### ISSUE THREAD

**Issue by de-mux** [mrname/haralyzer#4]
Starting from a clean virtual environment, haralyzer is installed successfully using `pip install haralyzer`.

However, trying to import the package in a script:
```python
import haralyzer
```

results in "`ImportError: No module named cached_property`". Manually installing cached_property solves the issue, so it seems it is just not getting installed by the package.

**Comment by mrname** [comment]
Yes, this does seem to be the case, even though it is listed in `setup.py`.

I am out of the country right now so I have limited internet access, but I will look into this as soon as possible. Thanks for your patience in the meantime (and of course, feel free to create a pull request if you do not want to wait).

**Comment by mrname** [comment]
Quite a stupid mistake:

https://github.com/mrname/haralyzer/commit/312f18a6212cc8c2b6bbe92d5e7d88954dbca6f4

All fixed up mate! Thanks for the heads up, and thanks for using `haralyzer`!

**Comment by mrname** [comment]
Everything working ok for you @de-mux ?

**Comment by de-mux** [comment]
All is well, thank you!
