### ISSUE TITLE
Harpage not work

### ISSUE THREAD

**Issue by valour01** [mrname/haralyzer#9]
I use the same code in your example to init the harpage object. But it seems that the harpage is empty. I am sure my har_data.har is okay. Because harpaser can work. Are you sure the harpage is available? The exception is below:

    ---------------------------------------------------------------------------
    IndexError                                Traceback (most recent call last)
    <ipython-input-54-0e8bd8f4ec02> in <module>()
    ----> 1 print har_page.url

    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site- packages/cached_property.pyc in __get__(self, obj, cls)
     24         if obj is None:
     25             return self
    ---> 26         value = obj.__dict__[self.func.__name__] = self.func(obj)
     27         return value
     28 

    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/haralyzer/assets.pyc in url(self)
    480         The absolute URL of the initial request.
    481         """
    --> 482         return self.entries[0]['request']['url']
    483 
    484     @cached_property

    IndexError: list index out of range

**Comment by mrname** [comment]
Bummer, could you hit me with a link to your raw HAR data?

**Comment by valour01** [comment]
This is [link](https://github.com/valour01/selenium). 
The code to init the object is totally the same as the example.

    with open('har_data.har', 'r') as f:
        har_page = HarPage('page_3', har_data=json.loads(f.read()))

I find the har_page.size is zero.

when I use the same har file to init the har_parser. It can work. So I don't think the problem is related to the har file itself. Maybe the page_id? I am not sure. Many Thanks

**Comment by mrname** [comment]
I think that is the case. Could you try using 'page_2' instead? If this
turns out to be the issue, I will add a catch for a page not found error.
Thanks!

**Comment by valour01** [comment]
page_2 seems work. I am sorry I still not understand why the page id shoud be page_2. If I have thousand of har files. How can I know the page id for each har file to init the harpage.

**Comment by mrname** [comment]
Unfortunately there is no way to know. When the har is generated it assigns
arbitrary IDs to the pages. For this reason, you probably want to make a
full parser and loop through parser.pages. you could look at the title of
the page or the URL to figure it which page you are dealing with. Did that
make sense? If that does not work for you, let me know what you need and I
might be able to add some features for you.

page_2 seems work. I am sorry I still not understand why the page id shoud
be page_2. If I have thousand of har files. How can I know the page id for
each har file to init the harpage.

—
Reply to this email directly or view it on GitHub
<https://github.com/mrname/haralyzer/issues/9#issuecomment-186883311>.

**Comment by mrname** [comment]
Sorry for the bad formatting @valour01 I was sending via email. Here is an example of what I mean:

```python
import json
from haralyzer import HarPage, HarParser

with open('har_data.har', 'r') as f:
    har_parser = HarParser(json.loads(f.read()))

 # See how many pages are in this HAR file
print 'num pages in har_file: {0}'.format(len(har_parser.pages))

# Check the URL of each page in the URL file
for page in har_parser.pages:
    print page.url
```

The output for your file would be

```
num pages in har_file: 1
https://imququ.com/beacon.html?tid=UA-5422922-2&dl=https%3A%2F%2Fimququ.com%2F&dt=JerryQu%20%E7%9A%84%E5%B0%8F%E7%AB%99&dr=&dp=%2F&ul=en-us&sd=24-bit&sr=1280x800&_=1455796412834
```

In most situations, a HAR file will have only one page, but in this sense, you can get the page you want without needing to know it's arbitrary id.

If you need to be working with lots of HAR files, I have been working on a REST API for storing and retrieving this data.

http://haralyzer-api.readthedocs.org/en/latest/

It is ALMOST done, but if it is something you need I can get back to work on it, or you could open a pull request.

Working up a better solution for page not found errors right now.

**Comment by mrname** [comment]
Let me know if you need any help here @valour01, otherwise I will go ahead and close this out.

**Comment by valour01** [comment]
Sorry for the late reply. My network doesn't work before. 
Actually, I have thousands of har files. And I want to get the detail information for each har file.

- how many requests the page have and the size, the http version info,server ip for each request/response.
- how many css/js/image/* the page have, the loading time and the size in total
- the time spent on dns, blocked, wait, connect etc.

At this moment, I don't know the page id for each har file. Do you know how to get the info above. Many Thanks

**Comment by mrname** [comment]
Sorry for the late response. So, you would want to do what I mentioned above, which is to use the full parser, and loop through it's `pages` attribute. Here is a code sample.

```python
import json
from haralyzer import HarParser

har_files = ['file_1.har', 'file_2.har']

for har_file in har_files:
    with open(har_file, 'r') as f:
        har_parser = HarParser(json.loads(f.read()))
    for page in har_parser.pages:
        #operate on the page
```

Does that make sense? If you have that many files it sounds like you will need something like the haralyzer API module I mentioned, so I will try to get back to work on that for you. :smile: 

In the meantime, you could always offload the data to CSV or something like that if you need to store it for later.

**Comment by valour01** [comment]
@mrname  Thank you very much. But it seems har_parser has less API compared with har_page. But I will have a try first. I may be back when I ran into some problems. Many thanks.

**Comment by mrname** [comment]
@valour01 sorry for any confusion.

In the example I gave, `har_parser.pages` is actually a `list` of `HarPage` objects. In this sense, you can create the parser and then access each page in the HAR file as a `HarPage` object without needing to care about the random `page_id` element. Does that make sense?

**Comment by valour01** [comment]
@mrname  Yes. I think this is exactly what I want. Thank you very much. I am going to try it.

**Comment by mrname** [comment]
I'm going to go ahead and close this out @valour01. Feel free to shoot me an email or open another issue if you need anything else. :smile: 

Enjoy `haralyzer`!
